### ISSUE TITLE
individual strange files

### ISSUE THREAD

**Issue by emylonas** [Brown-University-Library/iip-texts#121]
kqaz0001 - 2nd paragraph in support (l. 52)  - is it about the surface dimensions or is it about the writing or letters? Ideally it could be moved to one of those. 

yotv0001 line 210-216 - should the numbers be in the `<ex>` element or outside the `<expan>`? 

bshe0015  l. 182 `θ<ex>ε</ex>ίας` is either a supplied or a `sic/corr`?   l. 184 `τ<ex>ε</ex>ίχους`

bshe0019 l. 189 `<expan><abbr>τελ</abbr><ex>ε</ex><abbr>ίας</abbr></expan>`

bshe0012 l. 190 `<abbr>θ</abbr><ex>ε</ex><abbr>ίας</abbr>`, 208 `<abbr>τ</abbr><ex>ε</ex><abbr>ίχ</abbr><ex>ους</ex>`

bshe0014 l. 200 `<expan><abbr>τ</abbr><ex>ε</ex><abbr>ίχο<lb break="no" />υς</abbr></expan>` . l. 202 `<abbr>ἀν</abbr><ex>ε</ex><abbr>νεώθη</abbr></expan>`

bshe0029 l. 190 `Χ<ex>ε</ex>ιροθε<lb break="no"/>σία`

hamm0026 l. 147  `<expan><abbr>βοήθ</abbr><ex>ε</ex><abbr>ι</abbr></expan>`

hamm0032 . 144 `<expan><abbr>βοήθ</abbr><ex>ε</ex><abbr>ι</abbr>`

hamm0062 l. 150 `<expan><abbr>βοήθ</abbr><ex>ε</ex><abbr>ι</abbr></expan>`

hamm0001 misspelling of λουτροφορος.

hamm0002 translation is missing words, also, αγιος is missing accent

**Comment by GaiaLembi** [comment]
@emylonas 
**kqaz0001**: different measures at top and bottom (Shall we indicate that otherwise?)
**yotv0001**: outside, and that has been corrected. There is however an additional problem in that those text parts are absent from the diplomatic and are placed in the ears of the tabula ansata, which does not emerge from markup
The rest was either correct or has been corrected

**Comment by emylonas** [comment]
fixed. outliers moved to #147
