### ISSUE TITLE
.JPG vs. .jpg display issues

### ISSUE THREAD

**Issue by zeichman** [Brown-University-Library/iip-texts#154]
It seems that .JPG files cannot be displayed, whereas .jpg files can be displayed. I am dealing with this now and correcting files where it seems to be the case, but it applies to tqas0001 tqas0002 and tqas0003 at the moment. Once I correct them, this will no longer be visible.

**Comment by emylonas** [comment]
@zeichman is it a discrepancy between the upper/lowercase being different in the `<facsimile>` element and in the filename? there shouldn't be a problem displaying images that have a capitalized JPG extension, but the name has to match exactly and is case sensitive.

**Comment by zeichman** [comment]
@emylonas capitalization was the same for both the file name and in the xml encoding. That is, the issue is that it would not display if both were capital, but it would display if both were lowercase.

**Comment by emylonas** [comment]
This is happening because the IIP code isn't looking at the information in the `<facsimile>` element at all. It assumes that there is an image called "iip-id.jpg" for each inscription, and displays it if it exists, or shows the "no image" icon if not. 

This issue forms a part of also handling multiple images described in https://github.com/Brown-University-Library/iip-production/issues/105

**Comment by emylonas** [comment]
fixed in production repo
