### ISSUE TITLE
Files deleted or renamed - wordlist concerns

### ISSUE THREAD

**Issue by zeichman** [Brown-University-Library/iip-texts#184]
Renamed files (first has been deleted, second is the new file name)

Rehn0001 > reho0014
Knah0002 > cape0002
Halu0001 > elus0107
Hmti0004 > tibe0014
Shea0001 > bshe0161
Dora0002 > tdor0005
Jeru0237 > Jeru0591
Jent0006 > Jeru0558
anri0001 > unkn0137
knah0002 > cape0002

Merged files (transcription may be from one, but other information from the other).
Htmi0003 merged with tibe0004
Hmti0005 merged with tibe0005

**Comment by zeichman** [comment]
merged zoor0632 with zoor0416

**Comment by emylonas** [comment]
✓ Rehn0001 > reho0014
✓ Halu0001 > elus0107
✓ Hmti0004 > tibe0014
✓ Shea0001 > bshe0161
✓ Dora0002 > tdor0005
✓ Jeru0237 > Jeru0591
✓ anri0001 > unkn0137
✓ knah0002 > cape0002

Jent0006 > Jeru0558. _there is already an inscription with this number_

Merged files: 
merge zoor0362 with zoor0416
Htmi0003 merged with tibe0004
Hmti0005 merged with tibe0005

these may have to be done by Chris

**Comment by emylonas** [comment]
Questions to make this all clearer
I think the following files have been deleted - they still exist in the segmented files list - @emylonas will delete if they no longer exist in epidoc-files (but need an ok from @zeichman) 

jent0006.xml: I was going to rename this, but jeru0558 existed and looked very different - i didn't touch them. 
zoor0362.xml: should this be gone and  zoor0416 should have updated information?
jeru0496.xml:  deleted?
jeru0196.xml:  deleted?
hmti0003.xml: by merged do you mean that this file is gone, and tibe0004 has updated information? 
hmti0005.xml: by merged do you mean that this file is gone, and tibe0005 has updated information? 
knaf0004.xml:  deleted?

**Comment by zeichman** [comment]
Hi Elli,
This all looks correct to me. When I say "merged" means different things for different inscriptions, which I should have done a better job of describing. In general, though, it means one file was deleted and parts of it were put into an identical file that had the same inscription. In the case of Jent0006 and jeru0558, my initial assessment looks correct to me - the JENT file just transliterated the name and the jeru0558 file has an actual translation; the JENT file has the name twice in Hebrew, whereas the jeru file only lists it once. Is there something else that stands out to you as possibly indicating they're different files? It looks correct to me, though.

**Comment by emylonas** [comment]
merge zoor0362 with zoor0416 - no differences other than a bibliographic entry. If there were updates in the header of zoor0416, they were automatically copied, so ok.

Htmi0003 merged with tibe0004: this has some differences in the transcription div, and it's especially odd because each line is its own paragraph. Otherwise, there was additional bibliography, which I added to the merged file. if you open tibe0004 in Epidoc Files and look at the transcription - why are the paragraphs there?  Is it possible that someone entered it by pressing return in author mode, between lines? Even if the paragraphs are removed, there are some textual changes. You can go to Tools > Compare Files and compare the Epidoc Files tibe0004.xml with the one in 03HeaderMerged. Go ahead and make changes directly on the files. Btw, it's easiest to see the differences ifyou choose "XML Fast" from the leftnomst pulldown on the diff screen. That only looks for differences that actually change the XML, and ignores different white space. Play with the options. 

Hmti0005 merged with tibe0005: only difference was added bibliography. I added to merged file. All set.

**Comment by emylonas** [comment]
Jent0006 > Jeru0558 this has been reconciled. there was one difference in the translation. Might still need a look at the transcription

**Comment by emylonas** [comment]
Closing
