### ISSUE TITLE
Data display 

### ISSUE THREAD

**Issue by WennieZ** [Brown-University-Library/iip-texts#46]
There are a few discrepancies in the data that are resulting in the display being a little off on the website:

1. There are 10 inscriptions with physical type Amphora but 4 of them (susi0002, mare0019, mare0012, mare0011) have "amphora" as the physical type in the database and 6 of them (mare0001-mare0005, mare0008) have "Amphora" instead. All of these inscriptions should have "amphora" because all physical types are entered with the first letter in lowercase. 

2. In the options for "Type of Inscription" on the website, the options 'document', 'list', 'quotation', and 'signature' don't have the first letter capitalized which makes the appearance inconsistent with everything else in the box. I am unable to directly modify these options because Django is pulling the names from an XML library.

3. In the Material category, the subclasses for stone are displayed as "stone.marble" and "stone.limestone" instead of Stone (Marble) and Stone (Limestone).

**Comment by emylonas** [comment]
1 - fixed with commit 344a5ac  (9 files mare0001-0009)

The physical types and genres of the inscriptions are entered as unambiguous but not always human readable strings, and there is display text that is stored in an external file that is included via the xInclude mechanism. File is [http://cds.library.brown.edu/projects/iip/include_taxonomies.xml](http://cds.library.brown.edu/projects/iip/include_taxonomies.xml)

To fix 3, you can either look up the values in the external file when loading the display list or check to see if we index both fields. This is already being done in the original code, which substitutes the human readable display value for the more computable attribute value. 

2 has a few values that have not been vetted and therefore have not been assigned a display value. They will eventually be fixed and the incongruity will disappear.

**Comment by emylonas** [comment]
these have been fixed or are out of date. closing
